name: CI - lint, unit and E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-unit:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint --silent || true

      - name: Run unit tests
        run: npm run test:unit --silent || true

  contract-e2e:
    name: Contract E2E (fast)
    runs-on: ubuntu-latest
    needs: lint-and-unit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Start vite (background)
        run: |
          npx vite --port 5173 --host 127.0.0.1 &
          npx wait-on http://127.0.0.1:5173 -t 120000

      - name: Run contract Cypress specs
        uses: cypress-io/github-action@v6
        with:
          browser: edge
          spec: cypress/e2e/contract*.cy.js
        env:
          CYPRESS_baseUrl: http://127.0.0.1:5173

  full-e2e:
    name: Full E2E (Cypress)
    runs-on: ubuntu-latest
    needs: contract-e2e
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Start dev server
        run: |
          # Start Vite bound to 127.0.0.1 so wait-on can detect it reliably in the runner
          npx vite --port 5173 --host 127.0.0.1 &
          npx wait-on http://127.0.0.1:5173 -t 120000
        env:
          CI: true

      - name: Run full Cypress suite (headless)
        run: npx cypress run --browser electron

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ github.run_id }}
          path: |
            cypress/videos
            cypress/screenshots
            mochawesome-report || true
