name: Cypress E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-e2e:
    name: Run Cypress E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (action)
        uses: cypress-io/github-action@v5
        with:
          start: npx http-server ./ -p 8080
          wait-on: 'http://localhost:8080'
          browser: electron
          spec: 'cypress/e2e/**/*.cy.js'

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/**
            cypress/screenshots/**
