name: CI

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Vite requires Node.js >= 20.19; use a 20.x runner to satisfy this
          node-version: 20.19.0
      - name: Install Dependencies
        run: npm ci
      - name: Start Dev Server
        # Start vite in background bound to all interfaces
        run: npx vite --port 5173 --host 0.0.0.0 &
      - name: Wait for Server
        run: npx wait-on http://127.0.0.1:5173 -t 30000
      - name: Run Unit Tests
        run: npx vitest --run
      - name: Run Cypress E2E Tests
        run: npx cypress run --headless --browser electron
