name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Start Dev Server
        run: npm install -g pnpm && pnpm --silent dev &
      - name: Wait for Server
        run: npx wait-on http://localhost:5173 -t 30000
      - name: Run Unit Tests
        run: npx vitest --run
      - name: Run Cypress E2E Tests
        run: npx cypress run --headless --browser electron
